name = "ChainPlots"
uuid = "43761bbe-b505-42c3-b8bd-5d4ae40fd227"
authors = ["Ricardo Rosa <rmsrosa@gmail.com>"]
version = "0.1.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
julia = "1.6"
Flux = "0.12, 0.13"
Functors = "0.2"
Graphs = "1.6"
MetaGraphs = "0.7"
RecipesBase = "1.2"
